export const WEAPON_VARIABLE_SCORES = {
  SIGNATURE: 0, // Bias towards signature character
  DESIRED_STAT_MATCH_MULTIPLIER: 10,
  DESIRED_STAT_CRITS_MULTIPLIER: 2,
  BASE_ATTACK_REDUCER: 10,
}

export const WEAPON_SCORE_THRESHOLD = 60;