import { DomainOfForgery } from "@/common/models/domains";

export const CeciliaGarden = new DomainOfForgery(
  "Cecilia Garden",
  "The cecilia flowers that only grow on high cliffs once bloomed in the greenhouses here. The ancient civilization that once enjoyed the scent of the Cecilia was lost, and so too was the sea of white flowers",
  {
    1: `(Electro)`,
    2: `(Electro)`,
    3: `All party members gain an Electro DMG Bonus. (Electro)`,
    4: `All party members gain an Electro DMG Bonus. (Electro)`,
  },
  "Mondstadt"
);

export const HiddenPalaceOfLianshanFormula = new DomainOfForgery(
  "Hidden Palace of Lianshan Formula",
  "The operation of the Lianshan Formula created endless thunderstorms within the bowels of the mountain. It is said that the rumbling sounds of thunder that one hears outside the domain's gates call out to curious souls.",
  {
    1: `(Cryo)`,
    2: `(Cryo)`,
    3: `All party members gain a Cryo DMG Bonus. (Cryo)`,
    4: `All party members gain a Cryo DMG Bonus. (Cryo)`,
  },
  "Liyue"
);

export const CourtOfFlowingSand = new DomainOfForgery(
  "Court of Flowing Sand",
  "They say that in antediluvian times now lost to history, there was once a foolish ruler who dreamed of building a high garden in honor of the white sacred tree over the primordial sands. Now, dead silence fills the kingdom built on sand, but the obsessions of the past remain.",
  {
    1: `(Geo/Cryo)`,
    2: `(Geo/Cryo)`,
    3: `All characters' Shield Strength is increased. When a character obtains an Elemental Shard generated by a Geo Elemental Reaction, a shockwave will be unleashed, dealing DMG to enemies nearby. (Geo/Cryo)`,
    4: `All characters' Shield Strength is increased. When a character obtains an Elemental Shard generated by a Geo Elemental Reaction, a shockwave will be unleashed, dealing DMG to enemies nearby. (Geo/Cryo)`,
  },
  "Inazuma"
);

export const TowerOfAbjectPride = new DomainOfForgery(
  "Tower of Abject Pride",
  `It is said that the deserts were once home to three sage-kings, one of whom remained lovely and wise till the very end. They parted ways eventually for the sake of the paradise they sought in their hearts. This place is called a "tower", but in truth was the temporary residence of one of these people when they were building that earthly paradise. If one stretches the past back even further, it was once a small shrine built to avoid the wind and the sand.`,
  {
    1: `(Dendro/Electro)`,
    2: `(Dendro/Electro)`,
    3: `During the challenge, Quickened opponents will have all their Elemental RES decreased. (Dendro/Electro)`,
    4: `During the challenge, Quickened opponents will have all their Elemental RES decreased. (Dendro/Electro)`,
  },
  "Sumeru"
);

export const EchoesOftheDeepTides = new DomainOfForgery(
  "Echoes of the Deep Tides",
  "Legend speaks of a time in the distant past, when the Sovereign of the Waters had not yet returned from confinement, there was another God King who dreamed of building a prosperous empire out of harmonious music atop the waves. But the great ambition of building a utopia failed to come to fruition, and the arrogance of humanity sunk into their depths along with their pride. The golden melodies long silent, only the cold music of the tides still echoes upon the remains of their grand altars.",
  {
    1: `(Hydro/Pyro/Cryo/Anemo)`,
    2: `(Hydro/Pyro/Cryo/Anemo)`,
    3: `After a character triggers Hydro-related reactions, all party members will be granted a Hydro DMG Bonus. (Hydro/Pyro/Cryo/Anemo)`,
    4: `After a character triggers Hydro-related reactions, all party members will be granted a Hydro DMG Bonus. (Hydro/Pyro/Cryo/Anemo)`,
  },
  "Fontaine"
);

export const AncientWatchtower = new DomainOfForgery(
  "Ancient Watchtower",
  "Legend has it that in ancient times, the colossal beasts that roamed the land had a civilization of their own. After exploring the entirety of the land and surrounding sea, they built these structures in an attempt to cast their gaze upon the even wider world beyond. But these wise beasts have long since vanished, and in the present no one now knows the true purpose of this place.",
  {
    1: `(Hydro/Electro/Pyro/Anemo)`,
    2: `(Hydro/Electro/Pyro/Anemo)`,
    3: `When characters from Natlan are present, the party can trigger Nightsoul Burst in combat, using Ley Line Disorders to increase the DMG dealt by characters. (Hydro/Electro/Pyro/Anemo)`,
    4: `When characters from Natlan are present, the party can trigger Nightsoul Burst in combat, using Ley Line Disorders to increase the DMG dealt by characters. (Hydro/Electro/Pyro/Cryo)`,
  },
  "Natlan"
);

export const LostMooncourt = new DomainOfForgery(
  "Lost Mooncourt",
  "In those days, three moons caressed the earth with their silver light, and the lunar people knew the secrets of the lunar phases, being able to predict the tidal ebb and flow.\nWhatever they gently touched with their fingers would surge with moonlit might.Yet in the waning days, the moonlight dimmed, and the people, defenseless and leaderless, were scattered.Legend has it that the Frostmoon Scions constructed a lunar court in the border realms, summoning lost moonlight back to them.Today, that reflected light has disappeared from this forsaken altar.Where it once flowed through these stone carvings, there is now only frozen silence.Yet secrets unveiled in that quietude, perhaps the echoes of ancient oaths, still swirl about within the labyrinth of time.",
  {
    1: `(Dendro/Hydro/Electro/Pyro)`,
    2: `(Dendro/Hydro/Electro/Pyro)`,
    3: `Bloom, Hyperbloom, Burgeon and Lunar-Bloom reactions deal more DMG. (Dendro/Hydro/Electro/Pyro)`,
    4: `Bloom, Hyperbloom, Burgeon and Lunar-Bloom reactions deal more DMG. (Dendro/Hydro/Electro/Pyro)`,
  },
  'Nod-Krai'
);